.github/workflows/ost-of-ost.yaml

this will currently run basic-suite-master on el8stream against the PR

github: add /ost functionality

---

.github/README.md
.github/jenkins
common/helpers/ost-images.sh
common/scripts/check_broken_symlinks.sh
lagofy.sh

this will build a custom set of ost-images and then run
basic-suite-master on them

add support for ost-images CI

---

lagofy.sh

finally we have a working RHVH image, let's use it

use RHVH on rhel8 runs

---

ost_utils/vmconsole.py

Sometimes the vmconsole read hangs and so does the whole job. To avoid
leaving the job hanging forever a timeout will abort it if a read hangs
for more than 15 seconds.
Change-Id: Ibb835297e57b22b20d1331063711b2cad5cad58e

ost_utils: vmconsole - add timeout on read

---

common/deploy-scripts/setup_first_he_host.sh

This reverts:
commit d2e34164d54985a08c8d3a8b79a45d70e3d49971
Author: Yedidyah Bar David <didi@redhat.com>
Date:   Wed Nov 17 16:46:47 2021 +0200
Work around qemu-kvm 6.1.0 issue
https://gitlab.com/qemu-project/qemu/-/issues/641
Change-Id: I171610ca7d5507f076f3303fccda83bd16dbfbde

he: revert work around qemu-kvm 6.1.0 issue

---

network-suite-master/ovirtlib/sshlib.py
network-suite-master/test-scenarios/ovn-provider/test_ovn_provider.py

Refactor the test_ovn_provider and add retry for the ping from netns. 
The ping might not succeed on first try, add retry with timeout of 15 secs.

OVN provider tests

---

network-suite-master/testlib/suite.py
requirements.txt

Change-Id: Id2151659fc0d2781a1718d437da8c1a9a5dba647

network: replace deprecated distutils.Version

---

README.md

Since we moved to github we are not using jenkins.
Signed-off-by: Aviv Litman <alitman@redhat.com>

README: update the custom repo URL to github

---

common/helpers/ost-images.sh

Change-Id: Idc59781e21921bbe9adcc89cfd44065fb05cf115

Show ost-images rpm versions

---

ost_utils/pytest/fixtures/artifacts.py

use /var/tmp for collecting artifacts

---

common/deploy-scripts/setup_storage.sh
common/init-configs/1_engine_2_hosts.json

Currently, Except for HE, all suites use engine VM for storage,
add a separate VM for storage.

add storage vm to ost runs

---

common/deploy-scripts/setup_first_he_host.sh
ost_utils/pytest/fixtures/deployment.py

Reverts oVirt/ovirt-system-tests#85

Revert "Use nobest in 'DNF update the system'"

---

common/deploy-scripts/setup_engine.sh

this time due to not being able to run ansible as ovirt user

yet another workaroud for fapolicyd

---

ost_utils/pytest/fixtures/engine.py

Change-Id: Idf4d0d909d1ad5dd64bdb559db73c915f488c75a

Fix keycloak_enabled to work also if keycloak is missing

---

common/deploy-scripts/setup_first_he_host.sh

we do want to update stuff also for oVirt. And this way it should never
fail.

he: even better workaround for updating RHV appliance

---

ost_utils/pytest/fixtures/engine.py

even more simple is to just declare how it behaves.

Fix keycloak_enabled to work best

---

basic-suite-master/test-scenarios/conftest.py

use storage vm on basic suite

---

ost_utils/deployment_utils/package_mgmt.py

Avoid duplicated HTTP requests, while checking multiple workflow runs.

github: Improve custom repo expansion

---

lagofy.sh

lagofy: fix OST_DEPLOYMENT typo

---

common/deploy-scripts/setup_engine.sh
common/deploy-scripts/setup_first_he_host.sh

Disable downgrading postgresql-jdbc

---

ost_utils/pytest/fixtures/selenium.py

Change-Id: Ia6205538f1320e165f196b18e2d81ffd3962ae41

selenium: Use docker instead of podman

---

setup_for_ost.sh

since we use the ansible-core package in the playbook setup, Installing
Ansible can cause a dependency issue.

ost_setup: remove Ansible installation

---

ost_utils/pytest/fixtures/selenium.py

Switching to docker didn't improve the stability, so we're going back
to using podman.
Change-Id: I0c04b1e878dfc231a3abbdb4c133f6306008c364

selenium: Go back to using podman

---

ost_utils/selenium/navigation/driver.py

This is a follow-up patch to https://github.com/oVirt/ovirt-system-tests/pull/154. I am adding the comments from that patch as a separate comments to this patch.

Add ignoring of TimeoutException also to _wait_until

---

common/deploy-scripts/setup_storage.sh
common/deploy-scripts/setup_storage_he_extra.sh
common/init-configs/1_hosted_engine_2_hosts.json
he-basic-suite-master/test-scenarios/conftest.py

To maintain uniformity across all suites using storage VMs, add storage network and NICs.

he: add storage network for vms

---

common/deploy-scripts/setup_host.sh

Reverts oVirt/ovirt-system-tests#159

Revert "ost: downgrade nmstate"

---

ost_utils/deployment_utils/package_mgmt.py

We no longer use stdci jobs, so we don't need the code for finding RPM
repositories in jenkins links.

package_mgmt: Remove special jenkins repos handling

---

.github/jenkins

it needs to match the actual job parameters

update el[89]stream jobs with COPR updates

---

common/helpers/ost-images.sh

el9stream: Use el9-based node

---

common/deploy-scripts/setup_host.sh
ost_utils/pytest/fixtures/deployment.py

we do not use upgrade suite anymore, and the location for builds is
anyway no longer valid

clean up ovirt-node repos

---

basic-suite-master/test-scenarios/test_004_basic_sanity.py
basic-suite-master/test-scenarios/test_098_ovirt_provider_ovn.py

el9: Skip test broken by libvirt regression

---

network-suite-master/fixtures/engine.py

Change-Id: If779d55ab78467889fd61871bb6b71a854b78be2

network: enable debugging on engine.log, vdsm.log

---

common/deploy-scripts/setup_first_he_host.sh

Change-Id: I2a6fa8b7b5163adedcfcbfcb24ef980cfc34ae02

HE: Debug HE VM grub

---

ost_utils/selenium/page_objects/Grafana.py

Reverts oVirt/ovirt-system-tests#202 since we fixed the issue here: https://github.com/oVirt/ovirt-system-tests/pull/208

Revert "Run DB connection test for upstream only"

---

ost_utils/deployment_utils/package_mgmt.py

ovirt-engine builds are taking a long time and it's inconvenient to wait
until the build is finished before manually triggering the OST run using
"/ost" comment on the PR. If we find a relevant workflow run in progress
we can wait a minute and retry couple times, customizable by the new
GITHUB_WORKFLOW_TRIES variable.

simple github artifact retries for builds in progress

---

ost_utils/pytest/fixtures/deployment.py

Waiting for 'sshd' to be responsive is sometimes not enough.
We have cases of OST runs failing where 'sshd' is already responsive,
but 'NetworkManager' is still doing some configuration.
Change-Id: I5542971d6aef1f0a8eb2ec3d2acd006649c95570

deployment: Wait for 'default.target'

---

ost_utils/coverage/vdsm.py
ost_utils/deployment_utils/package_mgmt.py
ost_utils/pytest/fixtures/deployment.py

let's be more verbose on time consuming calls during deployment

improve deployment logging

---

ost_utils/selenium/page_objects/DisksListView.py
ost_utils/selenium/page_objects/EntityListView.py

Followup requested in https://github.com/oVirt/ovirt-system-tests/pull/236#pullrequestreview-1069729014

UI tests: change the calculation of disk status ID

---

basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py

Sometimes the creation of the selenium remote webdriver fails. This patch adds a retry logic for that.

UI tests: retry creating of the webdriver

---

basic-suite-master/test-scenarios/conftest.py
basic-suite-master/test-scenarios/test_002_bootstrap.py
basic-suite-master/test-scenarios/test_004_basic_sanity.py
basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py
ost_utils/constants.py
ost_utils/pytest/fixtures/defaults.py
ost_utils/pytest/fixtures/env.py
ost_utils/pytest/fixtures/storage.py

So that we can easily switch the type.

Take master SD type from env var

---

common/deploy-scripts/setup_first_he_host.sh
ost_utils/pytest/fixtures/deployment.py

Skips upgrade of ansible-core to prevent upgrade to ansible-core-2.13

Skip upgrade of ansible-core

---

ost_utils/vmconsole.py

Use python's signal to abort a vmconsole connection that is hanging forever.
Change-Id: I631f206b3f2fbf61dd0cd1f5337c4e58830fc18a

ost_utils: async abort of hanging connection

---

common/init-configs/1_engine_2_hosts.json

With hope that it will make Selenium crash more rarely.

storage: Increase the amount of RAM

---

ost_utils/pytest/fixtures/selenium.py
ost_utils/selenium/page_objects/DisksListView.py
ost_utils/selenium/page_objects/VmListView.py

- selenium: upgrade to 4.4.0
- selenium: export novnc port
- selenium: use Enter instead of clicking OK

selenium fix

---

ost_utils/selenium/page_objects/Grafana.py

el9strema Grafana changed the case of Test to test, it's enough to match
just the "Save & " part, that works on both el8 and el9

selenium: fix grafana changes on el9stream

---

ost_utils/pytest/fixtures/selenium.py

This patch adapts OST code to changes introduced by [1].
[1] https://github.com/oVirt/ost-images/pull/85

Adapt to new Selenium image naming

---

.github/jenkins

it will rebuild PR_URL ovirt-engine with rhv_build 1

jenkins: add rhv-build suite

---

.github/jenkins
.github/workflows/ost.yaml

- github: allow usage on push events
- github: try inputs instead
- github: use LAST_TRIGGERED_JOB_NAME

handle push

---

common/deploy-scripts/setup_first_he_host.sh
ost_utils/pytest/fixtures/deployment.py

This reverts commit 0e4ac168cd490e08c59c1c0ea1bf894fd8e27fb0.

Revert "Skip upgrade of ansible-core"

---

.github/workflows/check-docs.yaml
README.md
lagofy.sh
ost.sh

Change-Id: I680ed8a182f739a7f86b15e077ecaf77047c2802

ost.sh: Add lock command

---

common/deploy-scripts/setup_storage.sh

CHAP seems to be broken without it

Add authentication=1 to targetcli portal config
