oVirt/ovirt-system-tests

network-suite-master/ovirtlib/ansiblelib.py
With a mutable default value a function doesn't behave idempotently on
consecutive invocations.
Change-Id: I372bbc14459ae07cda200366a50dcc11dd9e4c7f
=> ovirtlib: ansiblelib - fix mutable default value

basic-suite-master/test-scenarios/test_002_bootstrap.py
basic: Temporarily disable openscap reports
We have two problems that make openscap reports fail currently:
- session locking with tmux
- chrony configuration
Let's xfail the test until we resolve them.
=> basic: Temporarily disable openscap reports

lagofy.sh
This can happen if the helper ost-images.sh gets aborted in the middle
of deploying custom images when it runs under root. We need to clean
up as root as well, but let's do that only when necessary, i.e. when we
cannot remove as current user.
=> lagofy: clean up with sudo when custom-ost-images have root permissions

common/deploy-scripts/setup_first_he_host.sh
This should no longer be needed:
commit 26ee8457e0fe9140d75a5d8e5bc12208c020be68
Author: Michal Skrivanek <michal.skrivanek@redhat.com>
Date:   Fri Oct 15 16:29:25 2021 +0200
he: copy imageio-client files to engine.
this is supposed to be a short-term hack to allow ansible to upload
cirros image to HE. On regular engine we inculde
ovirt-imageio-client
rpm but it's a bit cumbersome to push that to HE VM. We want to
change
this entirely to use imageio from pypi so this should be sufficient
for
now...
Change-Id: I35e12e4b3d0c83c04224144dafb736b449d9c4a7
Signed-off-by: Michal Skrivanek <michal.skrivanek@redhat.com>
=> revert imageio hack

network-suite-master/fixtures/engine.py
Extend the timeout since sometimes it is not enough causing flakiness in
runs.
Change-Id: Ib20bed9208c54f7c7c8b94f40683f56a7a3a3636
=> network: extend ServerRebootTimeout

ost_utils/coverage/vdsm.py
it seems that in the middle of the process of stopping vdsmd
systemd might already started stopping supervdsmd which vdsmd require.
this issue cause the vdsm coverage to break.
=> vdsm-coverage: fix vdsm coverage broken

.github/example-trigger.yaml, .github/workflows/ost-of-ost.yaml, .github/workflows/ost.yaml
similar to what we had on gerrit, this workflow can trigger different
suites and distros. The new agument "comment" takes the github comment
body in form "/ost[ <suite>[ <distro>]]".
=> github: parse suite and distro from trigger comment

basic-suite-master/test-scenarios/test_002_bootstrap.py
In Cluster 4.7 we now default to UEFI boot, that needs a bit more
memory.
=> he, basic: increase VM memory size for UEFI boot

basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py, ost_utils/selenium/page_objects/VmListView.py
This patch removes tests for the Export button on the vm list view. The reason is that we test only top level action buttons, and the export button has been moved to the kebab menu.
=> Remove test for export button

.github/workflows/ost.yaml
no need to run the job when comment doesn't start with /ost. Fails
faster and doesn't need runner's time.
=> github: reduce noise for non-OST comments

common/deploy-scripts/setup_first_he_host.sh
RHV appliance is often very outdated and it's missing packages. No need to enable for oVirt appliance that is being built regularly.
=> enable baseos&appstream repos on RHEL

common/deploy-scripts/setup_engine.sh, common/deploy-scripts/setup_host.sh
Anything that is denied by fapolicyd should be
logged to journal when the unit runs with
--debug-deny. This should help to identify
any "Operation not permitted" that might be related
to fapolicyd.
Signed-off-by: Ales Musil <amusil@redhat.com>
=> setup: Enably deny debug for fapolicyd

basic-suite-master/test-scenarios/test_002_bootstrap.py
The test for custom VDSM hook was highly dependent on the machine
configuration and could fail on non-standard setup (e.g. modified
umask). It is best to explicitly define what user and permissions we
expect on the hook file when deploying it.
Signed-off-by: Tomáš Golembiovský <tgolembi@redhat.com>
=> basic: fix VDSM hook permissions

ansible-suite-master/test-scenarios/conftest.py, ansible-suite-master/test-scenarios/test_002_ansible.py
Currently, ansible suite uses an engine for storage, using the storage VM
added in the previous patch.
=> use storage vm on ansible suite

common/deploy-scripts/setup_first_he_host.sh, ost_utils/pytest/fixtures/deployment.py
Without this, it fails, because it wants to update
ovirt-ansible-collection, which now requires
ansible-collection-ansible-utils, which requires ansible-core, whereas
the engine still conflicts with ansible-core.
TODO: Revert this (and perhaps some more) when the engine is fixed to
work with ansible-core.
Change-Id: I4851b76a353edd274cb4cfc76a0467b117f443c4
=> Use nobest in 'DNF update the system'

tox.ini
A recent version of click has been released which removes _unicodefun.
This resulted in inability to run ost.
Error:
File "/home/asocha/work/code/github.com/arso/ovirt-system-tests/.tox/black/lib/python3.9/site-packages/black/__init__.py", line 137
2, in patched_main
patch_click()
File "/home/asocha/work/code/github.com/arso/ovirt-system-tests/.tox/black/lib/python3.9/site-packages/black/__init__.py", line 135
8, in patch_click
from click import _unicodefun
ImportError: cannot import name '_unicodefun' from 'click' (/home/asocha/work/code/github.com/arso/ovirt-system-tests/.tox/black/lib/
python3.9/site-packages/click/__init__.py)
=> Click dependency fixed for black

ost_utils/deployment_utils/package_mgmt.py
Some projects have multiple runs, not all of which include artifacts.
We should therefore check for artifacts during the search for workflow
run corresponding to specific commit.
=> github: Fix custom repo artifact collection

.github/jenkins
packages are not preinstalled so when a PR is passed the verification
that it has been used would fail. Let's always skip that check and rely
on the suite tests to do the right thing (install whatever is needed)
=> jenkins: add exception for tr-suite-master

common/deploy-scripts/setup_tr_suite.sh, tr-suite-master/ost.json, tr-suite-master/test-scenarios/test_0001_check_installed_packages.py, tr-suite-master/test-scenarios/test_0002_init_terraform.py, tr-suite-master/test-scenarios/test_002_ansible.py, tr-suite-master/test-scenarios/test_003_go_ovirt_client.py, tr-suite-master/test-scenarios/test_004_run_ocp_installer.py
go-ovirt-client tests are working (unlike terraform ATM), so let's run
them!
=> tr: skip terraform tests and run go-ovirt-client instead

ost_utils/pytest/fixtures/artifacts.py
ansible is often broken, let's see what it tries to hide...
=> add ansible-runner temp directory to collected artifacts

basic-suite-master/test-scenarios/conftest.py, basic-suite-master/test-scenarios/test_002_bootstrap.py, basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py, ost_utils/keycloak.py, ost_utils/pytest/fixtures/engine.py, ost_utils/pytest/fixtures/keycloak.py, ost_utils/pytest/fixtures/sdk.py, ost_utils/selenium/page_objects/LoginScreen.py
This patch allows to test ovirt engine running with authentication
configured around internally bundled instance of Keycloak (OpenID
Protocol) that is deprecating AAA modules.
!! Work in progress - do not merge it yet !!
=> Support for internal Keycloak authentication

network-suite-master/fixtures/engine.py, network-suite-master/fixtures/providers.py, network-suite-master/test-scenarios/conftest.py
For upstream (el8stream) use engine credentials provided by internally
bundled Keycloak instance.
For downstream tests (rhel) stick to the legacy AAA
=> Engine's keycloak internal authentication support

he-basic-suite-master/test-scenarios/conftest.py, ost_utils/pytest/fixtures/engine.py
Without this patch, it fails on hosted-engine, where we currently
disabled it. Change the logic to check inside the engine machine instead
of guessing.
Change-Id: I681038351471af4747f61ed017fbf8c8e9a8d52a
=> Fix keycloak_enabled logic

common/deploy-scripts/setup_engine.sh
annoyingly enough, fapolicyd is enabled and unmasked by oscap --remediate during the run
=> fix workaround for fapolicyd

lagofy.sh
After renaming PREFIX variable we need to clean up the new
OST_DEPLOYMENT on ost_destroy to make switching envs easy.
=> lagofy: reset OST_DEPLOYMENT on destroy

ost_utils/pytest/fixtures/engine.py
otopi-config-query is great, but sometimes we have a single
config, sometimes we use conf.d subdirectory. KISS and just grep.
=> Fix keycloak_enabled to work better

network-suite-master/fixtures/engine.py, network-suite-master/test-scenarios/conftest.py
Some of the required fixtures are already available in ```ost_utils/pytest/fixtures/engine.py```
This patch removes duplicates and adds relevant imports.
=> Network suite: remove duplicated fixtures

lagofy.sh
actually, instead of unsetting in
01d8cb1e724d2f5e9f7da0e9839bbda69233ccb7 I should have just fixed the
regression in handling the former PREFIX variable introduced in
e1188fe1ca628fd55bb304d4d4095935b1fffc7b
=> lagofy: the right OST_DEPLOYMENT fix

common/deploy-scripts/setup_first_he_host.sh
Appliance rhvm-appliance-4.5-20220407 has ansible-core, no need for
ansible uninstallation
=> he: drop ansible upgrade workaround

network-suite-master/fixtures/ansible.py, network-suite-master/fixtures/storage.py, network-suite-master/test-scenarios/conftest.py
Currently, network suite uses an engine for storage, using the storage VM
added in the previous patch.
=> use storage vm on network suite

basic-suite-master/test-scenarios/test_099_aaa-ldap.py, common/init-configs/1_engine_2_hosts.json
Migrating the storage vm to a separate vm from the engine
also included moving the Ldap service to the storage vm.
=> basic: enable storage vm for ldap

ost_utils/pytest/fixtures/engine.py
With [1] we've disabled keycloak integration for now.
[1] https://github.com/oVirt/ovirt-engine/pull/273
=> engine: Disable usage of keycloak

he-basic-suite-master/test-scenarios/test_008_restart_he_vm.py
Some times, a short (3 minutes) timeout is not enough, in CI.
Change-Id: I63838b39820a63eae835809f93d30028f420cd98
=> he: test_008_restart_he_vm: Give the vm more time to shutdown

he-basic-suite-master/test-scenarios/test_001_he_deploy.py, ost_utils/pytest/fixtures/deployment.py
Engine is deployed later than other guests, so we delay the cusom repos
check until it's up.
=> he: Delay the custom repo check

common/init-configs/1_engine_2_hosts.json
remove storage disks from engine vm as all storage moved to the storage vm.
=> ost: remove storage disks from engine vm

lagofy.sh
8.6 uses 'ansible-core' and requires the additional galaxy packages
to be installed too.
=> lagofy: Fix ansible-galaxy setup

basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py
To avoid the necessity to sync browser versions in OST with
automatically updated Selenium grid images in ost-images we're switching
to "latest" browser versions.
=> selenium: Use "latest" browser versions

basic-suite-master/test-scenarios/test_004_basic_sanity.py
By default 'Popen' processes's stdout is opened as a byte stream.
Passing the 'universal_newlines=True' argument makes the stream
automatically decoded from UTF-8.
Since we're reading the output char by char, multibyte UTF-8 characters
can break the stream with i.e.:
E UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 191: invalid continuation byte
Let's change the output to have a form of bytes and use bytes in
comparisons too.
=> vmconsole: Don't decode stdout

ost_utils/pytest/fixtures/engine.py, ost_utils/pytest/fixtures/he.py
This patch re-enables keycloak support for both basic and he suites for non-rhel executions.
It's a merge of the following PRs:
- https://github.com/oVirt/ovirt-system-tests/pull/133
- https://github.com/oVirt/ovirt-system-tests/pull/124
Depends on: 
- https://github.com/oVirt/ovirt-engine/pull/295
- https://github.com/oVirt/ovirt-ansible-collection/pull/488
- https://github.com/oVirt/ovirt-hosted-engine-setup/pull/44
=> Enable keycloak for ost

requirements.txt
The newly released Selenium 4.1.5 version broke OST. Until we have a fix
let's use the older one.
=> selenium: Use specific version

basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py, ost_utils/pytest/fixtures/selenium.py, ost_utils/selenium/grid/__init__.py, ost_utils/selenium/grid/browser.py
In an attempt to limit the resources needed to run Selenium we're now using
the "standalone" images and running a single browser at a time.
[Related change](https://github.com/oVirt/ost-images/pull/53) on ost-images side.
Change-Id: Ic57391f70e22fb07bbbf441e7874fbf406d71232
=> selenium: Use standalone nodes running one at a time

ansible-suite-master/test-scenarios/conftest.py, hc-basic-suite-master/test-scenarios/conftest.py, he-basic-suite-master/test-scenarios/conftest.py, he-basic-suite-master/test-scenarios/test_001_he_deploy.py, network-suite-master/test-scenarios/conftest.py, ost_utils/pytest/fixtures/defaults.py, ost_utils/pytest/fixtures/deployment.py
In HE suite we don't want to touch engine until after HE deployment,
so in the past we used ansible_vms_to_deploy to exclude the engine.
Nowadays we add engine to ansible_all dynamically after the HE
deployment, so separate fixture is no longer needed.
=> HE: remove ansible_vms_to_deploy

ost_utils/pytest/fixtures/deployment.py
previous patch was not a proper revert, we also want to stop excluding this
package from dnf updates.
=> do not skip upgrade of postgresql-jdbc

common/helpers/ost-images.sh
As we currently don't have an el9 engine image, this hack will provide the
option to run el9 hosts with el8 engine.
=> run el9 hosts with el8 engine

common/deploy-scripts/setup_host.sh
workaround for BZ2084118, downgrading nmstate at el9 hosts.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2084118
=> ost: downgrade nmstate

basic-suite-master/test-scenarios/conftest.py, basic-suite-master/test-scenarios/test_002_bootstrap.py
We need to create the VMs without QXL devices in order to run them on EL9.
The patch removes devices that use spice/qxl.
=> run vms on el9

ost_utils/selenium/page_objects/Grafana.py
After the change in the Grafana UI we are no longer able to detect error messages displayed.
This patch updates the checks for errors in Grafana and also makes sure that the test fails if the notifications
list element is not detected - that could mean that the UI changed and we are not able to detect errors again.
It uses a very simple check - it only check if the notification contains string "Error". This is because the code does not really contain any other clue about the severity of the notification
```
<app-notifications-list class="page-alert-list">
<div>
<div class="css-1mkxr4d" aria-label="Alert error">
<div class="css-3p6jzl">
<div class="css-1vzus6i-Icon">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
viewBox="0 0 24 24" fill="currentColor" class="css-sr6nr"> …
```
=> Update Grafana check for error

basic-suite-master/test-scenarios/test_004_basic_sanity.py
There is no `async_` argument for the `add()` call in `ExternalVmImportService`. The argument is silently ignored and having that in the call is misleading/confusing to anyone reading the code.
Signed-off-by: Tomáš Golembiovský <tgolembi@redhat.com>
=> basic: remove async_ argument when calling ExternalVmImportService

basic-suite-master/test-scenarios/test_004_basic_sanity.py
Convert small raw disk to qcow with incremental backup enabled
=> add convert disk test

ost_utils/vmconsole.py
Align with PR#135 [1]:
By default 'Popen' processes's stdout is opened as a byte stream.
Passing the 'universal_newlines=True' argument makes the stream
automatically decoded from UTF-8.
Since we're reading the output char by char, multibyte UTF-8 characters
can break the stream with i.e.:
E UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda ...
invalid continuation byte
Let's change the output to have a form of bytes and use bytes in
comparisons too.
[1] https://github.com/oVirt/ovirt-system-tests/pull/135
Change-Id: I799faaa6617b7a1f48ce9175509eef1d7e62c4de
Change-Id: Ic550276233f6e1908c67d4c8a3cd9d7a05a5cd4a
=> ost_utils: vmconsole - use default byte stream

common/deploy-scripts/setup_engine.sh
Downgrade OVN to 21.12.0-46 on the engine machine so it matches the
latest available version for RHVH.
Change-Id: I6bc99e9d5aa0beb19a70d8f124407e0f7c7fffe4
Bug-Url: https://bugzilla.redhat.com/2091565
=> engine deploy: downgrade ovn - temp workaround

common/deploy-scripts/setup_engine.sh
=> setup_engine: Ignore errors on downgrade

ost_utils/vmconsole.py
When a VM misbehaves, e.g. very slow to respond, it sometimes sends
non-decodable bytes on the vmconsole connection stream. These bytes can
be ignored while waiting for the expected response.
Change-Id: Id4027103d609f42642e744387c80b3dccbd0ca43
=> ost_utils: vmconsole - ignore decode errors

common/deploy-scripts/setup_storage.sh
we do not have up to date LDAP configuration, legacy tooling has been
dropped on EL9 so we are skipping it for now, we anyway do not have
el9-based ovirt-engine yet
=> el9: skip 389-ds configuration

basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py, ost_utils/selenium/page_objects/VmPortal.py
The tests started to fail on logout due to the tooltip being displayed over menu item. This re-implementation should fix that.
=> Change logout from user portal

README.md
Without group 'libvirt', virsh says:
system policy prevents management of local virtualized systems
Change-Id: I66727d641244698ed1b702f5d2fd2415f890d6be
=> README: Note about permissions

he-basic-suite-master/test-scenarios/test_001_he_deploy.py, he-basic-suite-master/test-scenarios/test_008_restart_he_vm.py
Move test_set_global_maintenance to test_001, so that HE HA does not
interfere with other OST stuff. In particular, running OpenSCAP reports
on the hosts caused high CPU and memory load, which caused HA to stop
the engine VM.
Change-Id: Ib7cb415f003ac0b630f4f50e3dc54c568b2c296a
=> he: Run most tests under global maintenance

basic-suite-master/test-scenarios/test_003_00_metrics_bootstrap.py, ost_utils/assert_utils.py, ost_utils/utils.py
We're experiencing situations where the ansible playbook for configuring
metrics is hanging forever. This problem has been analyzed and it's most
probably an internal issue of either ansible-core or python interpreter. Since
it only seems to be an OST problem let's add a timeout and retries for this.
=> Workaround for metrics configuration ansible playbook hanging forever

ansible-suite-master/test-scenarios/conftest.py, basic-suite-master/test-scenarios/conftest.py, common/scripts/fetch_artifacts.yml, he-basic-suite-master/test-scenarios/test_001_he_deploy.py, lagofy.sh, network-suite-master/test-scenarios/conftest.py, ost.sh, ost_utils/pytest/fixtures/artifacts.py
While fixtures for collecting artifacts are very handy and work
really well, it's useful to have a tool for adhoc artifact
downloading to cover cases of OST runs that are hanging forever
in some place.
=> ost.sh: Add fetch-artifacts command

he-basic-suite-master/test-scenarios/test_001_he_deploy.py
During ost-images build we cache sar RPMs so they can be installed
offline on the HE. We don't have an el9stream based HE yet, so the
RPMs cached on el9stream hosts are not installable in this case.
Let's skip the sar installation for now when running on el9stream.
=> he: skip sar installation on el9stream hosts

basic-suite-master/test-scenarios/test_002_bootstrap.py
Add a health check after backup to delay tests until engine is healthy
=> check engine health after backup

basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py, ost_utils/pytest/fixtures/engine.py
We are using oVirt Engine Auth to connect to Grfana,
seems like there is no need in this method.
Signed-off-by: Aviv Litman <alitman@redhat.com>
=> UI: remove test_add_grafana_user method

basic-suite-master/test-scenarios/test_001_initialize_engine.py
PCI DSS openscap profile verifies checksums of files coming from RPMs.
Modified files are reported as a problem. We change the contents
of 'ovirt-engine.xml.in' file shipped as a part of 'ovirt-engine-backend'
RPM to enable debug logging on the engine.
Let's backup the file before changing it and restore the original after
engine setup.
=> engine: Restore original 'ovirt-engine.xml.in' after engine setup

common/libvirt-templates/vm_template
- Use cache='none' to avoid double caches on host and gust. With
cache='none' writes bypass the host page cache, and less memory is
used on the host for caching. This also enabled usage of io='native'.
- Use io='native' which is the recommended configuration. With this I/O
is submitted using single thread using libaio. This is usually faster
than io='threads', and more important for OST, it uses one thread
instead of multiple threads on qemu side, which keep the load on the
host lower. This can improve reliability and performance when running
many vms with few CPUs (as seem to happen in OST).
- Use discard='unmap' so discard requests punch holes in the images.
I'm not sure it is useful for qcow2 images but it is a good default,
in particular for developers running OST locally on small …
=> vm-template: Improve disk driver configuration

basic-suite-master/test-scenarios/test_002_bootstrap.py, common/libvirt-templates/vm_template
The root disk will be available in the guest as
/dev/disk/by-id/*-ost-root-disk
Instead of:
/dev/disk/by-id/*-1
=> vm-template: Nicer disk serial

lagofy.sh
The script was creating a qcow2 disk:
qemu-img create -f qcow2 -o preallocation=metadata disk.qcow2 100g
This creates an empty qcow2 image with preallocated metadata, so its
file size is actually 101G.
$ ls -lhs disk.qcow2
204M -rw-r--r--. 1 nsoffer nsoffer 101G Jul 21 16:52 disk.qcow2
But the disk xml is using raw format:
<disk type='file' device='disk'>
<driver name='qemu' type='raw' cache='writeback' discard='unmap'/>
<source file='/home/jenkins/workspace/ds-ost-baremetal_manual/deployment/images/storage-sda.qcow2' index='2'/>
...
</disk>
So the VM is using the disk as a 101G raw image, overwriting the qcow2
header with actual guest data:
image: /home/jenkins/workspace/ds-ost-baremetal_manual/deployment/images/storage-sda.qcow2
file format: raw
virtual size: 101 GiB (108464701440 …
=> lagofy.sh: Fix extra disks format

common/libvirt-templates/disk_template, common/libvirt-templates/vm_template
Use the same configuration for the disk_template as we use for the root
disk in vm_template. This is more important since the storage vm does
more I/O.
Fixes e2453ad536ef (vm-template: Improve disk driver configuration)
=> Improve disk_template driver configuration

network-suite-master/fixtures/engine.py
Requires: oVirt/ovirt-engine#553
Change-Id: I64f11c501fbf7e2fde388b2f7a97149c77dea031
=> network: use drop-in logging config file for engine debug

basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py, ost_utils/selenium/navigation/driver.py, ost_utils/selenium/page_objects/DashboardView.py, ost_utils/selenium/page_objects/DisksListView.py, ost_utils/selenium/page_objects/Displayable.py, ost_utils/selenium/page_objects/EntityListView.py, ost_utils/selenium/page_objects/Grafana.py, ost_utils/selenium/page_objects/GrafanaLoginScreen.py, ost_utils/selenium/page_objects/LoginScreen.py, ost_utils/selenium/page_objects/VmDetailView.py, ost_utils/selenium/page_objects/VmPortal.py, ost_utils/selenium/page_objects/WebAdminLeftMenu.py, ost_utils/selenium/page_objects/WebAdminTopMenu.py, ost_utils/selenium/page_objects/WelcomeScreen.py, ost_utils/selenium/page_objects/WithBreadcrumbs.py, ost_utils/selenium/page_objects/WithNotifications.py
UI tests: do not allow direct access to selenium webdriver
This patch makes the selenium driver instance private so that the clients are forced to use ovirt driver. This way we can better handle specific errors. The patch enhances the find_element(s) method with retry for known issues
=> Hide driver

ost_utils/selenium/navigation/driver.py, ost_utils/selenium/page_objects/WebAdminTopMenu.py, ost_utils/selenium/page_objects/WelcomeScreen.py
Sometimes when logging out, instead of displaying the welcome screen, the page stays on dashboard. Probable cause is that some queries are still running and interrupt the page redirect.
This page manually refreshes the webadmin so that the welcome screen is displayed.
=> UI tests: Improve logout

basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py, ost_utils/selenium/page_objects/WebAdminTopMenu.py, ost_utils/selenium/page_objects/WelcomeScreen.py
After the logout, the behavior is not deterministic. Sometimes is the user redirected to welcome screen, sometimes to login screen and somtimes it stays on the Webadmin dashboard for a while.
This patch navigates to the welcome screen after pressing log out, and if necessary, reloads and waits until the user is logged out.
=> UI tests: Move directly to welcome screen after logout

basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py
Sometimes, when closing the dialog, the validations might take a while. We should therefore wait for the list views to be displayed before continuing further with the tests.
=> UI tests: wait for the list view after closing the dialog

basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py, ost_utils/selenium/page_objects/EventsView.py
During the cluster upgrade, it is possible to have either "Check for update of host XY" or "Update of host XY" messages.
Both are correct from the test point of view (we do not care if the update is actually performed, we want to make sure
that both hosts are checked for update / updated)
=> UI tests: change checked messages for cluster upgrade

basic-suite-master/test-scenarios/test_002_bootstrap.py, common/deploy-scripts/setup_engine.sh
Verify that snmp traps works after restart
This patch verifies that SNMP traps are still working after
ovirt-engine-notifier and snmptrapd services are restarted.
First the services are restarted, then a new tag "notifiertag" is added to
the system, finally we check that a trap generated on the new tag created is
logged to snmptrapd.log
We have to set the configuration value DAYS_TO_SEND_ON_STARTUP to 1 in engine setup
because its default value is 0, it means that it will not send any old events,
a race between the service start and the new "notifiertag" tag will cause that this
event will not be processed.
=> Test that notifier works after restart

basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py, ost_utils/selenium/navigation/driver.py
When using Keycloak, the tests sometimes fail because the user is not logged out properly and the admin
stays logged in.
=> UI tests: fix problem with logout from webadmin

requirements.txt
we stopped using it completely because it was not reliable
=> requirements: drop ansible-navigator

common/helpers/ost-images.sh
now that we build el9stream engine and have the corresponding image, we can
run el9stream runs with it
=> lagofy: use el9stream-engine-installed

basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py, ost_utils/selenium/page_objects/VmListView.py
The make new template was failing with the lates Selenium. This patch creates one action chain for setting the name and pressing OK button.
=> UI tests: Make new template

ost_utils/selenium/page_objects/VmPortal.py
After migrating VM Portal to PatternFly4 the CSS class used by the
spinner component has changed to "pf-c-spinner".
The new class should be checked together with the old class to ensure
smooth transition from PF3 to PF4.
=> Check VM Portal status based on presence of Refresh button

basic-suite-master/test-scenarios/test_004_basic_sanity.py, basic-suite-master/test-scenarios/test_098_ovirt_provider_ovn.py
The bug mentioned in the comment has been fixed.
=> ovn: Reenable test on el9stream

basic-suite-master/test-scenarios/test_002_bootstrap.py, common/deploy-scripts/setup_engine.sh
This patch verifies that SNMP traps are still working after ovirt-engine-notifier and snmptrapd services are restarted.
First the services are restarted, then a new tag "notifiertag" is added to the system, finally we check that a trap generated on the new tag created is logged to snmptrapd.log
We have to set the configuration value DAYS_TO_SEND_ON_STARTUP to 1 in engine setup because its default value is 0, it means that it will not send any old events, a race between the service start and the new "notifiertag" tag will cause that this event will not be processed.
This patch was tested on upstream (el8) and downstream (rhel8)
Signed-off-by: Eli Mesika <emesika@redhat.com>
=> Verify that snmp traps works after restart

basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py
=> Set Selenium timeouts explicitly

basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py
logout from webadmin and logging back to web-ui under a different user
does not work correctly with keycloak, credentials/identity is being
cached by selenium and we can't figure out how to flush that...let's
just swap the order of tests so it doesn't happen in the first place.
=> ui: move web-ui portal test to the beginning

basic-suite-master/test-scenarios/test_100_basic_ui_sanity.py, ost_utils/selenium/navigation/driver.py
From time to time Selenium server hangs indefinitely on http requests
made by client. Looking at the logs it seems that the netty code sees
the http request, but somehow it never reaches the code that handles the
response.
The client side blocks until it gets a response from the server.
The timeout for this path seems to be 5 mins. On the server side
however, the timeout for an inactive session to be killed is set
to 3 mins by default. That combination creates an undesired effect -
before the client realizes that the http request may have been stuck for
too long, the server already kills its session.
This patch shortens the client timeout for waiting on http
responses to 30 secs. Unfortunately, with current client implementation
in Selenium library, it's not possible to change this value …
=> Fix selenium timeouts

ost_utils/selenium/navigation/driver.py, ost_utils/selenium/page_objects/ClusterListView.py, ost_utils/selenium/page_objects/ClusterUpgradeDialog.py, ost_utils/selenium/page_objects/VmDetailView.py, ost_utils/selenium/page_objects/WithOvirtDriver.py
To accommodate PR https://github.com/oVirt/ovirt-engine-ui-extensions/pull/73 that uses shadow DOM to render modals from ovirt-engine-ui-extensions, adjust the selenium tests to use the `shadow_root` when necessary.  Querying elements from the base document do not recurse into shadow-roots.  See https://github.com/oVirt/ovirt-engine-ui-extensions/pull/73#issuecomment-1259760170 for more explanation.
Some more info on shadow dom in selenium: https://titusfortner.com/2021/11/22/shadow-dom-selenium.html
The changes will be backwards compatible with non shadow dom modals.
Change details:
`driver`
- add type info so Intellisense works within the class
- add `find_dialog_root`, `find_dialog_element` and related functions to more easily handle testing of dialogs/modals/popups
- enhance …
=> Use `shadow_root` for ui-extensions modals

network-suite-master/test-scenarios/ovn-provider/test_ovn_provider.py, network-suite-master/test-scenarios/ovs/test_ovn_physnet.py
OVN connectivity does not work on el9.
Change-Id: I692b4e21b4a37e6164f06cae74e92b3f18e75cc7
=> network: xfail on el9 due to no connectivity

lagofy.sh
In CI we may get many concurrent runs and when it happens it stacks up
and evetually takes longer than 2 minutes, when that happens the lock is
released and code continues and clashes with ongoing creation/destroy.
Let's try longer timeout, 10 minutes should be enough for everyone.
=> lagofy: hold the destroy&create lock longer

common/deploy-scripts/setup_first_he_host.sh, ost_utils/pytest/fixtures/deployment.py
Downgrade java-11-openjdk-headless to 11.0.15.0.10-3 to workaround
following error during keycloak setup:
Failed to load truststore: /etc/pki/ovirt-engine/.truststore
=> Downgrade openjdk to workaround keycloak setup issue

network-suite-master/test-scenarios/ovn-provider/test_ovn_provider.py, network-suite-master/test-scenarios/ovs/test_ovn_physnet.py
OVN connectivity does not work on el9 due to BZ #2144834.
=> Revert: network: xfail on el9 due to no connectivity

common/deploy-scripts/setup_host.sh
Problems with nested VMs' firmware are hard to debug. A dump of firmware
log is very helpful with that, so let's have it on by default in OST.
Initially the console logs were only set up for HE, but having them
for all the VMs helps a lot too.
Needs https://github.com/oVirt/ost-images/pull/91 to work properly.
=> Dump console and firmware logs for all VMs

requirements.txt
Openstacksdk>=0.62.0 is now published on pypi. Use it going forward.
Change-Id: I26a094b522202ace8c5e0d30749571a46d5d25d9
=> requirements.txt: use specific openstacksdk commit 

network-suite-master/ovirtlib/virtlib.py
Adjust VM memory size in network suite to align with adjustments in basic suite [1].
[1] https://github.com/oVirt/ovirt-system-tests/
commit/1d0bf8cfc7e6678f19e85089e58790ad35b3c53c
Change-Id: I70ffe291c807c809a482dd29f9bfdb5a2235dfbc
=> network: adjust memory sizes for VMs

he-basic-suite-master/test-scenarios/test_012_local_maintenance_sdk.py
Fails too much, not trivial to fix.
Change-Id: I0967b1523f03eb6d1b166c5cb174807818704387
=> he: test_012_local_maintenance_sdk: xfail

basic-suite-master/test-scenarios/test_002_bootstrap.py, ost_utils/ansible/collection.py
The image_template did not start the playbook from engine but from some
diffrent place. With this patch the playbook is copied to the engine and
started there.
=> ansible: Start image_template from engine

ost_utils/pytest/fixtures/selenium.py
OST started complaining that `{selenium_remote_artifacts_dir}` doesn't exist. We never created it by ourselves, so it's probable some new podman version changed behavior in this regard.
=> selenium: Create artifacts dir manually

tox.ini
'check-readthedocs' action uses 'ubuntu:latest' image underneath. This one has py3.10 installed, so let's change the job definition in tox.
=> docs: Fix GitHub job

ost_utils/pytest/fixtures/selenium.py
The directory is created with root:root and 755 permissions. Chrome container runs under 'seluser', so it's lacking write permissions.
=> selenium: Change permissions on artifacts dir

common/deploy-scripts/setup_engine.sh
Allows Grafana to connect to PostgreSQL datasource, for example
ovirt_engine_history database.
=> Allow Grafana connecting to PostgreSQL

.github/workflows/ost.yaml
el8stream is not functional due to ansible breakage for a while, el9stream works fine.
=> run OST on el9stream by default

basic-suite-master/test-scenarios/test_099_aaa-ldap.py
With CentOS Stream 8 EOL and CentOS Stream 9 ldap setup not ready, keeping ldap test only on rhel8.
=> Disable ldap test out of rhel8

.github/workflows/ost.yaml, ost_utils/deployment_utils/package_mgmt.py
- Allow to provide multiple pr urls (csv) to be able to test multiple PRs. OST already supported this by providing multiple `--custom-repo` flags
- Allow to run an OST suite with the code in a PR on ovirt-system-tests (code needs to be on a branch on oVirt org)
=> Multiple custom repos + ost on ost PRs

basic-suite-master/test-scenarios/test_002_bootstrap.py
Add a video device with the new VideoType argument. Also re-enable the skipped test.
=> basic: add new video device with VideoType
